### ISSUE TITLE
Example not working with Wow.exe or Starcraft II.exe

### ISSUE THREAD

**Issue by nakohnen** [Andrey1994/game_overlay_sdk#4]
When I try to test with both Blizzard games I get the following error :

[2019-09-18 21:20:39.859] [monitorLogger] [info] Trying to start executable xxx\StarCraft II\StarCraft II.exe with args: 
[2019-09-18 21:20:39.909] [monitorLogger] [error] failed to create maped file Error 5
Traceback (most recent call last):
  File "xxx/inject_game.py", line 74, in <module>
    hook_wow()
  File "xxx/inject_game.py", line 60, in hook_wow
    game_overlay_sdk.injector.run_process(exe_path=path)
  File "xxx\game_overlay_sdk\injector.py", line 158, in run_process
    raise InjectionError ('failed to run process please check logs', res)
game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 failed to run process please check logs

I did not build the project. I downloaded your project from GitHub and copied the python folder as I saw the DLLs are in there too.

**Comment by Andrey1994** [comment]
looks like #3 , did you run it with admin priviligies?

**Comment by Andrey1994** [comment]
Also I dont know which Graphical API is used in starcraft and wow, this lib works only with dx11 dx12 and vulkan

**Comment by nakohnen** [comment]
Wow should use either d3d12 or 11 depending on version Classic/Retail. I have not run it as Admin. Looking into it. I'll keep you updated.

**Comment by nakohnen** [comment]
It went way better with Admin rights. However I got this output instead : 
```
[2019-09-18 22:05:47.142] [monitorLogger] [info] Trying to start executable E:\Blizzard Games\World of Warcraft\_classic_\Wow.exe with args:
[2019-09-18 22:05:47.152] [recordLogger] [info] Using DLL I:\OneDrive\projects\Telepathy\Programm\game_overlay_sdk\lib\GameOverlay64.dll for process 19272
[2019-09-18 22:05:47.152] [recordLogger] [info] starting injection to process 19272
[2019-09-18 22:05:47.152] [recordLogger] [info] got handle for process 19272
[2019-09-18 22:05:47.152] [recordLogger] [info] acquired remote dll address for 19272 address is 0x187d3250000
[2019-09-18 22:05:47.444] [recordLogger] [error] Remote thread failed, exit code is 0 error is0
[2019-09-18 22:05:47.444] [recordLogger] [info] injected
Press Enter to stop...
[2019-09-18 22:06:09.465] [recordLogger] [info] Using DLL I:\OneDrive\projects\Telepathy\Programm\game_overlay_sdk\lib\GameOverlay64.dll for process 19272
[2019-09-18 22:06:09.489] [recordLogger] [info] starting free dll from process 19272
[2019-09-18 22:06:09.489] [recordLogger] [info] got handle for process 19272
[2019-09-18 22:06:09.491] [recordLogger] [error] unable to find module in process 19272
[2019-09-18 22:06:09.491] [monitorLogger] [error] failed to free library
Traceback (most recent call last):
  File "I:\OneDrive\projects\Telepathy\Programm\inject.py", line 74, in <module>
    hook_wow()
  File "I:\OneDrive\projects\Telepathy\Programm\inject.py", line 70, in hook_wow
    game_overlay_sdk.injector.release_resources()
  File "I:\OneDrive\projects\Telepathy\Programm\game_overlay_sdk\injector.py", line 107, in release_resources
    raise InjectionError('stop monitoring error', res)
game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 stop monitoring error
Drücken Sie eine beliebige Taste . . .
```

**Comment by Andrey1994** [comment]
I've just installed wow and can not reproduce it locally, I've downloaded the latest version of game_overlay_sdk from PYPI and it works fine
![Screenshot](https://live.staticflickr.com/65535/48760705541_0912e498ee_b.jpg)

```
>python examples\create.py --exe_path "D:\World of Warcraft\_retail_\Wow.exe"
WARNING:root:For Steam Games please provide app id or ensure that there is steam_appid.txt file in game folder! You can get app_id here https://steamdb.info/search/
INFO:root:writing None to D:\World of Warcraft\_retail_\steam_appid.txt
[2019-09-19 20:27:10.426] [monitorLogger] [info] Trying to start executable D:\World of Warcraft\_retail_\Wow.exe with args:
[2019-09-19 20:27:10.430] [recordLogger] [info] Using DLL C:\Users\a1994\AppData\Local\Programs\Python\Python36\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 16484
[2019-09-19 20:27:10.430] [recordLogger] [info] starting injection to process 16484
[2019-09-19 20:27:10.430] [recordLogger] [info] got handle for process 16484
[2019-09-19 20:27:10.431] [recordLogger] [info] acquired remote dll address for 16484 address is 0x13207400000
[2019-09-19 20:27:10.829] [recordLogger] [info] injected
Press Enter to stop...[2019-09-19 20:27:38.849] [monitorLogger] [error] target process was terminated, dont send message
WARNING:root:target process was stopped
```

**Comment by nakohnen** [comment]
Nice! I tried it with WoW Classic and it didnt work. Could you try WoW Classic too? You can select it as a wow version under the Wow tab, it's a dropdown over the launch button in the Blizzard launcher.

EDIT: Can I do a feature request? Could you grab the swapchain and build a screenshot function which returns an Numpy image object back to python? I can write the Numpy part if you wish, I just need an image from the swapchain as a function/method.

**Comment by Andrey1994** [comment]
for screenshots I have another library which doesnt hook inside game process and much more stable because of this https://github.com/Andrey1994/screen_recorder_sdk and it can record a video. Also you can check https://github.com/Andrey1994/game_inspector and https://github.com/Andrey1994/fps_inspector_sdk

**Comment by Andrey1994** [comment]
seems like I will need to download classic to check, I think you can try with _retail and game_overlay_sdk downloaded from pypi in the meantime. And I've run retail with disabled battle net launcher, not sure that it matters but its possible

**Comment by nakohnen** [comment]
Is it possible then to capture only the game window, even if it's not in focus and behind other windows?
My goal is to multibox WoW and extract vital information and send it to my main character, so I know when to switch to the window of other character. As I play my main character the other window needs to be in the background.

**Comment by Andrey1994** [comment]
if your game window is not a full screen for screenshots it will cut it and keep only game window, but if there are windows on top of your game window you will see them.(it takes a texture of entire desktop, finds game window position and crops everything else but it can not handle window overlapping)

**Comment by nakohnen** [comment]
If you hook the directx library (present function or swapchain texture file) you can grab the rendered image from the game itself. Then it makes no difference if the game window is behind other windows. That's how for example the OBS streaming software does it. My skills in C/C++ are not good enough to implement it myself. I was quite happy when I saw your hooking library.

**Comment by Andrey1994** [comment]
I guess if you play in full screen mode your game window has exclusive access to the desktop and Desktop Window Manager doesnt work during it and second game will render nothing at this time

**Comment by nakohnen** [comment]
It is possible to grab the image from background/hidden window. There is a Multiboxing software which does that (ISBoxer -> Video FX feature), however it costs money (subscription) and I want to do it myself from python so I can add my code/features as well.

**Comment by Andrey1994** [comment]
Maybe it uses Nvidia Capture SDK(https://us.battle.net/forums/en/wow/topic/20752486240 nvfbc is a part of this SDK) but unfortunately this SDK is not available for Geforce GPUs without secret GUID from Nvidia

**Comment by Andrey1994** [comment]
"It is possible to grab the image from background/hidden window" in windowed mode or borderless windowed mode - yes. But note sure for full screen

**Comment by nakohnen** [comment]
Yes you are right. So if I play on borderless fullscreen it should in theory be possible.

The ISBoxer does this without the requirement of nvidia gfx-card.

**Comment by Andrey1994** [comment]
It's doable and the easiest option - call D3DXSaveSurfaceToFile, just need to add a command to take a screenshot and send it via memory mapped file which I use for communication between two processes and add new python method which will send this command and convert resulting file to a numpy array. And I hope there is smth like D3DXSaveSurfaceToFile in Vulkan too

The only issue here - its very specific case and unfortunately this project is not popular on github, so I can not promise that I will do it soon

**Comment by nakohnen** [comment]
You could advertise this library as a streaming SDK with this feature and it could become very popular as it would be the only Python library to my knowledge that can do this. 

I searched a whole week to find your project which is only related to my needs.

Edit: I will poke around your C source files maybe I could get something to work. If I get it working I'll do a pull request. My C skills are very rusty though.

**Comment by Andrey1994** [comment]
screen_recorder_sdk suits much more for streaming sdk and in both cases a lot of work will be required to record sound as well

**Comment by nakohnen** [comment]
True, but the standard streaming method is to only stream the game window (even if in background) so the viewers cannot see personal information if the streamer alt-tabs to another application. I'm not sure, maybe the OBS source has something on capturing surface on vulkan.

**Comment by nakohnen** [comment]
I tried with retail WoW too and it still does not work.

```
C:\WINDOWS\system32>python C:\Users\Lobo\Desktop\inject.py
[2019-09-20 20:26:35.539] [monitorLogger] [info] Trying to start executable E:\Blizzard Games\World of Warcraft\_retail_\Wow.exe with args:
[2019-09-20 20:26:35.550] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 15472
[2019-09-20 20:26:35.550] [recordLogger] [info] starting injection to process 15472
[2019-09-20 20:26:35.551] [recordLogger] [info] got handle for process 15472
[2019-09-20 20:26:35.551] [recordLogger] [info] acquired remote dll address for 15472 address is 0x11642ed0000
[2019-09-20 20:26:35.885] [recordLogger] [error] Remote thread failed, exit code is 0 error is0
[2019-09-20 20:26:35.885] [recordLogger] [info] injected
```

**Comment by Andrey1994** [comment]
for me it works, you can try to install from pypi and disable wow launcher

**Comment by nakohnen** [comment]
Ran it with PowerShell with admin rights and without the blizzard launcher : 

```
PS C:\WINDOWS\system32> pip --version
pip 19.2.3 from c:\python37\lib\site-packages\pip (python 3.7)
PS C:\WINDOWS\system32> pip3 --version
pip 19.2.3 from c:\python37\lib\site-packages\pip (python 3.7)
PS C:\WINDOWS\system32> pip install game-overlay-sdk
Requirement already satisfied: game-overlay-sdk in c:\python37\lib\site-packages (1.0.1)
Requirement already satisfied: numpy in c:\python37\lib\site-packages (from game-overlay-sdk) (1.17.2)
PS C:\WINDOWS\system32> pip install --upgrade --force-reinstall game-overlay-sdk
Collecting game-overlay-sdk
  Using cached https://files.pythonhosted.org/packages/cd/96/a3a139dfbd08a75e6b7459ba909ef2a76a1a080b93cce617c516a4cd3f2d/game_overlay_sdk-1.0.1-py3-none-any.whl
Collecting numpy (from game-overlay-sdk)
  Using cached https://files.pythonhosted.org/packages/bd/51/7df1a3858ff0465f760b482514f1292836f8be08d84aba411b48dda72fa9/numpy-1.17.2-cp37-cp37m-win_amd64.whl
Installing collected packages: numpy, game-overlay-sdk
  Found existing installation: numpy 1.17.2
    Uninstalling numpy-1.17.2:
      Successfully uninstalled numpy-1.17.2
  Found existing installation: game-overlay-sdk 1.0.1
    Uninstalling game-overlay-sdk-1.0.1:
      Successfully uninstalled game-overlay-sdk-1.0.1
Successfully installed game-overlay-sdk-1.0.1 numpy-1.17.2
PS C:\WINDOWS\system32> python --version
Python 3.7.3
PS C:\WINDOWS\system32> python I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py --exe_path "E:\Blizzard Games\World of Warcraft\_retail_\Wow.exe"
WARNING:root:For Steam Games please provide app id or ensure that there is steam_appid.txt file in game folder! You can get app_id here https://steamdb.info/search/
INFO:root:writing None to E:\Blizzard Games\World of Warcraft\_retail_\steam_appid.txt
[2019-09-20 20:44:41.434] [monitorLogger] [info] Trying to start executable E:\Blizzard Games\World of Warcraft\_retail_\Wow.exe with args:
[2019-09-20 20:44:41.446] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 11392
[2019-09-20 20:44:41.446] [recordLogger] [info] starting injection to process 11392
[2019-09-20 20:44:41.447] [recordLogger] [info] got handle for process 11392
[2019-09-20 20:44:41.447] [recordLogger] [info] acquired remote dll address for 11392 address is 0x12444bb0000
[2019-09-20 20:44:41.778] [recordLogger] [error] Remote thread failed, exit code is 0 error is0
[2019-09-20 20:44:41.778] [recordLogger] [info] injected
Press Enter to stop...
[2019-09-20 20:44:56.787] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 11392
[2019-09-20 20:44:56.816] [recordLogger] [info] starting free dll from process 11392
[2019-09-20 20:44:56.816] [recordLogger] [info] got handle for process 11392
[2019-09-20 20:44:56.819] [recordLogger] [error] unable to find module in process 11392
[2019-09-20 20:44:56.819] [monitorLogger] [error] failed to free library
Traceback (most recent call last):
  File "I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py", line 55, in <module>
    main ()
  File "I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py", line 51, in main
    game_overlay_sdk.injector.release_resources ()
  File "C:\Python37\lib\site-packages\game_overlay_sdk\injector.py", line 104, in release_resources
    raise InjectionError ('stop monitoring error', res)
game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 stop monitoring error
```

It appears that the game launches after the error already produced, I see an error in the terminal before the main game window even shows up.

If I launch the game first and then listen for it via monitor :

```
PS C:\WINDOWS\system32> python I:\OneDrive\projects\game_overlay_sdk-master\python\examples\monitor.py --name Wow.exe
WARNING:root:For Steam Games ensure that there is steam_appid.txt file in \%SteamFolder\%\steamapps\common\\%GameName\% with correct appid! You can get app_id here https://steamdb.info/search/
[2019-09-20 20:51:16.181] [monitorLogger] [error] No process to draw overlay
```

He does not find the process even though I have it clearly listed under details in the task manager.

**Comment by Andrey1994** [comment]
monitor means that you run monitor first and after that run game

**Comment by Andrey1994** [comment]
I run it without powershell just plain cmd, not sure that its the issue but worth to try

**Comment by nakohnen** [comment]
I tried with monitor and cmd just like you said:
```
C:\WINDOWS\system32>python I:\OneDrive\projects\game_overlay_sdk-master\python\examples\monitor.py --name Wow.exe
WARNING:root:For Steam Games ensure that there is steam_appid.txt file in \%SteamFolder\%\steamapps\common\\%GameName\% with correct appid! You can get app_id here https://steamdb.info/search/
Press Enter to stop...[2019-09-20 21:15:53.427] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:15:58.428] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:03.430] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:08.432] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:13.370] [monitorLogger] [info] Target Process created, name Wow.exe, pid 5740, architecture 64
[2019-09-20 21:16:13.370] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 5740
[2019-09-20 21:16:13.398] [recordLogger] [info] starting injection to process 5740
[2019-09-20 21:16:13.399] [recordLogger] [info] got handle for process 5740
[2019-09-20 21:16:13.399] [recordLogger] [info] acquired remote dll address for 5740 address is 0x20e698a0000
[2019-09-20 21:16:13.434] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:18.438] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:23.440] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:28.441] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
[2019-09-20 21:16:33.442] [monitorLogger] [error] No process to draw overlay
WARNING:root:target process is not created
```

The game window does not show up. However, I can find it in the task manager. This is weird.

**Comment by Andrey1994** [comment]
I am aware of such issues with monitor it can hang. but create mode works stable for me, just run it one more time
```
E:\game_overlay_sdk\python>python examples\create.py --exe_path "D:\World of War
craft\_retail_\Wow.exe"
WARNING:root:For Steam Games please provide app id or ensure that there is steam_appid.txt file in game folder! You can get app_id here https://steamdb.info/search/
INFO:root:writing None to D:\World of Warcraft\_retail_\steam_appid.txt
[2019-09-20 21:22:55.632] [monitorLogger] [info] Trying to start executable D:\World of Warcraft\_retail_\Wow.exe with args:
[2019-09-20 21:22:55.843] [recordLogger] [info] Using DLL C:\Users\a1994\AppData\Local\Programs\Python\Python36\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 15916
[2019-09-20 21:22:55.843] [recordLogger] [info] starting injection to process 15916
[2019-09-20 21:22:55.844] [recordLogger] [info] got handle for process 15916
[2019-09-20 21:22:55.844] [recordLogger] [info] acquired remote dll address for 15916 address is 0x1878e9f0000
[2019-09-20 21:22:57.895] [recordLogger] [info] injected
Press Enter to stop...
```

**Comment by nakohnen** [comment]
Same result:
```
C:\WINDOWS\system32>python I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py --exe_path "E:\Blizzard Games\World of Warcraft\_retail_\Wow.exe"
WARNING:root:For Steam Games please provide app id or ensure that there is steam_appid.txt file in game folder! You can get app_id here https://steamdb.info/search/
INFO:root:writing None to E:\Blizzard Games\World of Warcraft\_retail_\steam_appid.txt
[2019-09-20 21:34:20.650] [monitorLogger] [info] Trying to start executable E:\Blizzard Games\World of Warcraft\_retail_\Wow.exe with args:
[2019-09-20 21:34:20.660] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 1468
[2019-09-20 21:34:20.660] [recordLogger] [info] starting injection to process 1468
[2019-09-20 21:34:20.660] [recordLogger] [info] got handle for process 1468
[2019-09-20 21:34:20.660] [recordLogger] [info] acquired remote dll address for 1468 address is 0x143dff40000
[2019-09-20 21:34:20.984] [recordLogger] [error] Remote thread failed, exit code is 0 error is0
[2019-09-20 21:34:20.984] [recordLogger] [info] injected
Press Enter to stop...
[2019-09-20 21:34:39.995] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 1468
[2019-09-20 21:34:40.020] [recordLogger] [info] starting free dll from process 1468
[2019-09-20 21:34:40.020] [recordLogger] [info] got handle for process 1468
[2019-09-20 21:34:40.021] [recordLogger] [error] unable to find module in process 1468
[2019-09-20 21:34:40.021] [monitorLogger] [error] failed to free library
Traceback (most recent call last):
  File "I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py", line 55, in <module>
    main ()
  File "I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py", line 51, in main
    game_overlay_sdk.injector.release_resources ()
  File "C:\Python37\lib\site-packages\game_overlay_sdk\injector.py", line 104, in release_resources
    raise InjectionError ('stop monitoring error', res)
game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 stop monitoring error
```

This is so weird. It feels like the game is protected or something...

With Battlefield V it is the same thing:

```
C:\WINDOWS\system32>python I:\OneDrive\projects\game_overlay_sdk-master\python\examples\create.py --exe_path "E:\Origin Games\Battlefield V\bfv.exe"
WARNING:root:For Steam Games please provide app id or ensure that there is steam_appid.txt file in game folder! You can get app_id here https://steamdb.info/search/
INFO:root:writing None to E:\Origin Games\Battlefield V\steam_appid.txt
[2019-09-20 21:37:33.248] [monitorLogger] [info] Trying to start executable E:\Origin Games\Battlefield V\bfv.exe with args:
[2019-09-20 21:37:33.258] [recordLogger] [info] Using DLL C:\Python37\lib\site-packages\game_overlay_sdk\lib\GameOverlay64.dll for process 15096
[2019-09-20 21:37:33.258] [recordLogger] [info] starting injection to process 15096
[2019-09-20 21:37:33.259] [recordLogger] [info] got handle for process 15096
[2019-09-20 21:37:33.259] [recordLogger] [info] acquired remote dll address for 15096 address is 0x180000
[2019-09-20 21:37:33.290] [recordLogger] [error] Remote thread failed, exit code is 0 error is0
[2019-09-20 21:37:33.290] [recordLogger] [info] injected
Press Enter to stop...[2019-09-20 21:37:34.293] [monitorLogger] [error] target process was terminated, dont send message
```

**Comment by Andrey1994** [comment]
is it possible that you have streamer or smth else enabled which hooks d3d api too and load libraries to game process?

**Comment by nakohnen** [comment]
<img width="1920" alt="screenshot" src="https://user-images.githubusercontent.com/1585379/65355956-849e1800-dbf3-11e9-86df-fe4152046a05.png">
Finally! I reinstalled all dependencies (i.e. Vulkan) and now it works!

**Comment by nakohnen** [comment]
However I am still interested to get screenshots directly from the hooked directx library. I tried this:

 ```
OverlayThread.cpp

   void OverlayThread::ThreadProc ()
    {
        RecordingState::GetInstance ().Start ();
        HANDLE mapFile =
            OpenFileMapping (FILE_MAP_ALL_ACCESS, FALSE, TEXT ("Global\\GameOverlayMap"));
        HANDLE mapCommandsFile =
            OpenFileMapping (FILE_MAP_ALL_ACCESS, FALSE, TEXT ("Global\\GameOverlayMapCommand");
        HANDLE mapTextureFile =
            OpenFileMapping (FILE_MAP_ALL_ACCESS, FALSE, TEXT ("Global\\GameOverlayMapTexture"));

        if (mapFile == NULL or mapCommandsFile == NULL or mapTextureFile == NULL)
        {
            g_messageLog.LogError ("OverlayThread", "Failed to open file mapping", GetLastError ());
        }
        g_messageLog.LogInfo ("OverlayThread", "Opened mapped files");
        while (!this->quit_)
        {
            if (mapFile)
            {
                char *buf = (char *)MapViewOfFile (mapFile, FILE_MAP_ALL_ACCESS, 0, 0, 4096);
                if (buf)
                {
                    RecordingState::GetInstance ().SetOverlayMessage (buf);
                    UnmapViewOfFile (buf);
                }
                else
                {
                    g_messageLog.LogError ("OverlayThread", "Failed to read from mapped file");
                }
            }

            if (mapCommandsFile && mapTextureFile)
            {
                char *buf = (char *)MapViewOfFile (mapCommandsFile, FILE_MAP_ALL_ACCESS, 0, 0 4096);
                if (strcmp(buf, "SCREENSHOT") == 0 ) {

                }
                    char *buf_pic = (char *)MapViewOfFile (mapTextureFile, FILE_MAP_ALL_ACCESS, 0, 0, 4096);
                    D3DXSaveSurfaceToFile()
                }
            }

            Sleep (200);
        }
    }
```

But now I'm stuck. I do not know enough of C to know how to correctly write to the mapped file and determine the correct buffer size. 

PS: Im going away for 4 days, so I can't test things on my PC.

**Comment by zitonDev** [comment]
> 
> 
> <img alt="screenshot" width="1920" src="https://user-images.githubusercontent.com/1585379/65355956-849e1800-dbf3-11e9-86df-fe4152046a05.png">
> Finally! I reinstalled all dependencies (i.e. Vulkan) and now it works!

Dependencies as in using pip? I'm having exact same issue with other app could you please tell me which dependencies you installed.

**Comment by Andrey1994** [comment]
Vulkan SDK / runtime there is a link in readme to download them

**Comment by zitonDev** [comment]
> 
> 
> Vulkan SDK / runtime there is a link in readme to download them

No luck I'm trying to get it to work with Valorant, it launches the game but I get this error. I'm doing it in Admin CMD so I can't seem to grasp on what else there is wrong.

`C:\Users\vorte\Desktop\Python_Projects\zVal\Overlaytest>python mon.py --exe_path "C:\Riot Games\Riot Client\RiotClientServices.exe" --exe_args "--launch-product=valorant --launch-patchline=live"
[2020-07-02 10:11:57.597] [monitorLogger] [info] Trying to start executable C:\Riot Games\Riot Client\RiotClientServices.exe with args: --launch-product=valorant --launch-patchline=live
[2020-07-02 10:11:57.602] [recordLogger] [info] Using DLL C:\Python38\lib\site-packages\game_overlay_sdk\lib\GameOverlay32.dll for process 9808
[2020-07-02 10:11:57.602] [recordLogger] [info] starting injection to process 9808
[2020-07-02 10:11:57.602] [recordLogger] [info] got handle for process 9808
[2020-07-02 10:11:57.603] [recordLogger] [info] acquired remote dll address for 9808 address is 0x4c20000
[2020-07-02 10:11:57.605] [recordLogger] [error] Remote thread failed, exit code is 0 error is0
[2020-07-02 10:11:57.605] [recordLogger] [info] injected
Press Enter to stop...
[2020-07-02 10:13:29.783] [recordLogger] [info] Using DLL C:\Python38\lib\site-packages\game_overlay_sdk\lib\GameOverlay32.dll for process 9808
[2020-07-02 10:13:29.812] [recordLogger] [info] starting free dll from process 9808
[2020-07-02 10:13:29.812] [recordLogger] [info] got handle for process 9808
[2020-07-02 10:13:29.812] [recordLogger] [error] unable to find module in process 9808
[2020-07-02 10:13:29.812] [monitorLogger] [error] failed to free library
Traceback (most recent call last):
  File "mon.py", line 54, in <module>
    main ()
  File "mon.py", line 50, in main
    game_overlay_sdk.injector.release_resources ()
  File "C:\Python38\lib\site-packages\game_overlay_sdk\injector.py", line 104, in release_resources
    raise InjectionError ('stop monitoring error', res)
game_overlay_sdk.injector.InjectionError: GENERAL_ERROR:4 stop monitoring error

C:\Users\vorte\Desktop\Python_Projects\zVal\Overlaytest>`

**Comment by Andrey1994** [comment]
What is RiotClientServices.exe? DLL should be injected to the game process, while it looks like launcher

**Comment by zitonDev** [comment]
RiotClientServices.exe is like the launcher. I can't directly launch the game because it gives me a permission error even if run it as administrator.
![Windows](https://i.gyazo.com/ef5ef2c15ede8e38a4020bf7d7561913.png)

**Comment by Andrey1994** [comment]
for tun_process need to find a way to launch directly otherwise it will not work.
you can try start_monitor instead run_process(check examples) but its not reliable and may not work or lead to deadlock

**Comment by zitonDev** [comment]
> 
> 
> for tun_process need to find a way to launch directly otherwise it will not work.
> you can try start_monitor instead run_process(check examples) but its not reliable and may not work or lead to deadlock

Yea none of those work Valorant has a rootkit anticheat so working around it is very hard it's probably blocking the run process and start monitor from working. Dang it I can't even make a basic fps counter for my game now.

**Comment by Andrey1994** [comment]
use this for fps counter https://github.com/Andrey1994/fps_inspector_sdk
I can bet any money it will measure fps

**Comment by Andrey1994** [comment]
but wo overlay

**Comment by zitonDev** [comment]
> 
> 
> but wo overlay

Yup script worked w/o overlay. I'm not familiar with C but if you can please look into seeing if there is any way you could have an overlay over Valorant because if you get that done it'll be quite impressing tbh.
